Use argparse
jun-sforzando/PAC2020 pull request #7
Opened 2020-08-22 16:48 UTC by jun-sforzando

## Describe the PR

To close #2 .
Add argparse

## Screenshots

<img width="576" alt="Screen Shot 2020-08-23 at 1 25 54" src="https://user-images.githubusercontent.com/67792139/90961072-3bc8a080-e4e1-11ea-80a6-c823fb102551.png">

## Detail of the change

Set the default value of `main()` in `main.py` with `argparse`.

2020-08-23 04:16 UTC, tomoya-sforzando requested changes
`argparse` の利用に関して、README.mdの更新も必要ですね。
README.mdがそもそも壊れていますが、その修正はいつやりますか？こちらのPRより先に、README.mdの修正Issueを立てて、先にやっつけてしまいます？

2020-08-23 05:16 UTC, tomoya-sforzando requested changes
README.mdが適切な内容でないので修正をお願いします

2020-08-23 06:33 UTC, tomoya-sforzando reviewed
もうちょっとだけ直しましょうか。

2020-08-23 06:54 UTC, tomoya-sforzando approved these changes

2020-08-23 06:54 UTC, merged

2020-08-25 09:09 UTC, shin-sforzando commented
@jun-sforzando https://sforzando.slack.com/archives/C016HFFU4SW/p1598175821037000?thread_ts=1598173684.033300&cid=C016HFFU4SW